### PR TITLE
 Revise deprecation clause (close #12)

### LINKED ISSUE #12: Revise deprecation clause
# Current state

The 7th clause of the PVP currently states:

> *Deprecation*. Deprecated entities (via a `DEPRECATED` pragma) *SHOULD* be
counted as removed for the purposes of upgrading the API, because packages that
use `-Werror` will be broken by the deprecation. In other words the new *A.B*
**SHOULD** be greater than the previous *A.B*.

Quoting RFC2119:

> SHOULD   This word, or the adjective "RECOMMENDED", mean that there
>   may exist valid reasons in particular circumstances to ignore a
>   particular item, but the full implications must be understood and
>   carefully weighed before choosing a different course.

# Proposed change

Requiring a major version increment for deprecation seems overkill, as nowadays having `-Werror` enabled by default is rejected on Hackage uploads. Thereby the original rationale makes little sense, as a new deprecation annotation/warning does not cause compilation break, nor does it represent a semantic change. Hence a major version signal is not sensible.

"Recommend" only a minor version bump (so that the deprecation warning can be acted upon guarded by `MIN_VERSION_foo(a,b,c)` macros, which can only access the major+minor version components.

Suggested rewording:

> *Deprecation*. Deprecated entities (via a `DEPRECATED` pragma) *SHOULD* be counted as a *non-breaking change*. In other words, the new *A.B* **MAY** remain the same but the new *C* **SHOULD** be greater than the old *C*.

# History

This clause was added back in [2011-06-28](https://wiki.haskell.org/index.php?title=Package_versioning_policy&diff=40683&oldid=37378) and the change comment says merely

> discussion on #haskell suggested deprecation = removal

Going through the IRC logs, the conversation that lead to that change took place earlier on the same day (UTC+2 timestamps):

```
02:34 < benmachine> so guys, if I'm deprecating things in a module, what effect should that have on the version number of the next release?
02:35 < edwardk> removed functionality should cause the major version # to bump
02:35 < benmachine> sure, but it's not removed
02:36 < edwardk> the major version # are the x & y out of x.y.z.w
02:36 < benmachine> it's still there, but it just spits a warning if you use it
02:36 < dankna> I think deprecation ought to count as removal for that purpose, but I have no idea what the standard says
02:36 < benmachine> I mean deprecating as in the pragam
02:36 < identity_> what about minor API change?
02:36 < identity_> e.g. not backwards compatible change
02:36 < benmachine> dankna: the PVP page on the wiki doesn't know about the deprecate pragma
02:36 < dankna> I see
02:36 < tommd> benmachine: I don't think the PVP says anything, but I'd bump the C (in A.B.C.D versions)
02:36 < edwardk> i'd probably still bump the major version. the reason being that -Wall will crap out
02:36 < benmachine> edwardk: you mean -Werror?
02:37 < edwardk> and virtually everyone who builds on cabal builds with -Werror or -Wall
02:37 < edwardk> yeah
02:37 < aavogt> people widely use -Werror?
02:37 < benmachine> ho hum
02:37 < benmachine> I don't
02:37  * identity_ doesn't
02:37  * identity_ didn't know
02:37 < tommd> That's news to me
02:37 < edwardk> i use -Wall everywhere at least
02:37 < gfarfl> iwtu: actually, since Map.insert takes a key and a value, you need to change that to (uncurry insert (key,value))
02:37 < benmachine> enough people do that I'm inclined to agree with edwardk
02:38 < benmachine> which means I just screwed up :P oh well
02:38 < benmachine> (I released 0.4.0.1 with two things deprecated)
02:38 < benmachine> over 0.4
02:38 < benmachine> so auxiliary question: can I get a version "unreleased"?
02:39 < benmachine> almost certainly overkill in this case
02:39 < benmachine> but would be nice to know
```

### PR DESCRIPTION
**Pull request by sol**
(as suggested by @hvr)

### CODE REVIEW

**Comment by chreekat** [comment]
Anything I can do to help move this along?

**Comment by hvr** [comment]
@chreekat Well, I did already float this to the CLC over a year ago at https://groups.google.com/forum/#!topic/haskell-core-libraries/HCAepXp0NKg but there wasn't a clear resolution yet as the CLC members didn't speak out. So he next step would be to try to get the CLC members to express an opinion, by writing a mail to the haskell-core-libaries list.  If there's no objections from the CLC, we can move on to announce this to the community wide libraries list and maybe CC to haskell-cafe, and after say 2-3 weeks implement it and release it as part of "PVP 1.1"

**Comment by sol** [comment]
That sounds like a lot of pain to get changes into the PVP.  That would not be a problem per se if the PVP would already represent some sort of community consensus.  But that is not the case.  At least parts of the PVP are highly controversial.

**Comment by chreekat** [comment]
@hvr I see that Kmett is on the CLC and gave a thumbs up in #12 itself. Plus, the conversation in the thread you linked looks entirely positive. You yourself are a Hackage trustee. Can you help clarify what a PR on this repo needs in order to be merged?

Unlike @sol, I think nailing down the process and making it efficient is actually pretty important for open source, volunteer projects. I have a little bit of experience in that sort of thing, which is why I am trying to be of assistance. If I need to send another email to the CLC I want to ask the right questions. However, I suspect it isn't actually necessary. (I also have no opinion on the merits of the PVP itself.)

**Comment by hvr** [comment]
@chreekat well, let me try to reach out to some CLC members directly; I'll report back

**Comment by chreekat** [comment]
Ok! Sounds good.

**Comment by RyanGlScott** [comment]
In case you need a CLC member :+1:, this has my support.

**Comment by hvr** [comment]
I'll have take care of #19 as a pre-req first (which I intend to do soon); then we can go forward with this one.

**Comment by m-renaud** [comment]
I just submitted an merge request to GHC (see [here](https://gitlab.haskell.org/ghc/ghc/merge_requests/89)) which changes the behaviour of `-Werror` to no longer fail compilation if a `DEPRECATED` symbol or module is used (unless explicitly requested with `-Werror=deprecations`).

This addresses one of the largest concerns I've heard raised about not bumping a major version when adding a `DEPRECATED` pragma, namely that because so many folks use `-Werror`, without a major version bump it would break a lot of builds.

I'm completely in favour of this policy change since a deprecation is only meant to inform users about planned changes in **upcoming** releases and shouldn't affect the buildability of the current major version. Of course, we'll need to wait for whatever version of GHC that gets released in (if accepted) to reach wide adoption, but its better than never fixing it!

**Pull request closed without merging**
